solve: spreadOperatorMaxValue
pkiop/JS-Array-Challenge pull request #89
Opened 2021-05-19 14:03 UTC by uhj1993

2021-05-19 14:19 UTC, pkiop requested changes
README보면 새로운 방식으로 테스트하도록 바꿨습니다! 

본인 레포지토리에서 PR만들어서 pkiop:master -> 본인:master 로 PR날려서 머지해서 본인레퍼지토리 최신화 한다음 새 양식에 맞게 올려주세요!

2021-05-20 11:51 UTC, uhj1993 commented
이렇게 하는 게 맞을까요? 그리고 npm run test 할 때 다른 분들 것도 같이 test 되느라 시간이 좀 오래 걸리는 느낌인데 정답 테스트 할 때마다 test 돌리는 게 시간이 너무 지체되는 느낌인데 제 것만 채점 가능하게 할 수는 없을까요? 
![image](https://user-images.githubusercontent.com/72803184/118973872-1fdd2700-b9ad-11eb-9165-8843aa4023a8.png)

2021-05-20 11:57 UTC, pkiop commented
네 이것 맞습니다!
그부분 한번 고민해서 자기것만 할 수 있게 안내해드릴게요!

명령어를 npm run test 말고
jest ./Challenge/uhj1993 이렇게 하면 본인 것만 테스트 하긴 합니다!

2021-05-20 11:57 UTC, merged

2021-05-20 11:59 UTC, pkiop commented
본인 문제 푼 폴더로 들어가서 `jest ` 이렇게 하면 푼 문제만 테스트 할 수도 있습니다!