findWord, expDivOdd(다시풀기)
pkiop/JS-Array-Challenge pull request #93
Opened 2021-05-20 14:00 UTC by dongmin3891

2021-05-20 14:33 UTC, pkiop commented
다시 푸시는 김에 문제 다시 복사해서 테스트할 수 있도록 수정하면 좋을 것 같아요!

2021-05-23 02:32 UTC, pkiop requested changes
readme 참고해서 테스트할 수 있도록 수정해주세요!

2021-05-24 14:02 UTC, dongmin3891 commented
어떻게 하는건지 잘모르겠어요....

2021-05-25 12:24 UTC, pkiop commented
본인 레퍼지토리에서 Pull request 누르시고

![image](https://user-images.githubusercontent.com/34783156/119497391-7aa4c300-bd9f-11eb-80c5-f15dc83f5d2e.png)

여기 compare across link 누르시고 

pkiop:master -> 본인: master 
이렇게 PR한번 날려서 동기화 하신다음 문제푸시면 됩니다~

2021-05-31 14:21 UTC, dongmin3891 commented
죄송합니다.. 조금 더 자세히 설명 부탁드릴 수 있을까요? PR을 날리는 버튼같은게 안보여요..

2021-05-31 14:39 UTC, pkiop commented
@dongmin3891 
![image](https://user-images.githubusercontent.com/34783156/120209264-6feba180-c269-11eb-8a82-c7d1e2034e2f.png)
본인 레퍼지토리에서 이거 누르고 
![image](https://user-images.githubusercontent.com/34783156/120209315-7c6ffa00-c269-11eb-8a46-da72eb51e1c2.png)
new pull request 누르시면 저거 나옵니다!

2021-05-31 14:58 UTC, dongmin3891 commented
감사합니다. 지금은 동기화 잘 된건가요??!!

2021-05-31 15:07 UTC, dongmin3891 commented
![캡처1](https://user-images.githubusercontent.com/65215746/120212159-9fe87400-c26c-11eb-95a3-0e98cb31de83.PNG)
![캡처2](https://user-images.githubusercontent.com/65215746/120212163-a119a100-c26c-11eb-8a0d-fa306d52ba8a.PNG)

제 레퍼지토리에 들어가서 pull request 누르면 첫번째 사진처럼 나오구 
NEW pull request를 누르면 두번째 사진처럼 나옵니다.  
pkiop님께서 말씀하신 부분이 제 레퍼지토리 pull request에 들어가서
pkiop : master-> 본인 : master 이렇게 설정하고 pr을 보낸다는게 뭘 눌러서 보내는건지 잘 모르겠어요 
일단 이것저것 해봤는데 깃허브 잔디밭은 채워졌네요 ㅠ

2021-05-31 15:41 UTC, pkiop commented
제일 마지막 사진에서 베이스 레퍼지토리를 반대로 하고 PR날려서 머지 하시면 됩니다!😊

2021-06-02 13:25 UTC, closed without merging